### ISSUE TITLE
Separar a classe WeaponsDetector

### ISSUE THREAD

**Issue by braiansmarzaro** [RodolfoFR/yolo_ei#4]
A classe possui informações de _people_ e de _weapon_. O ideal é que a classe seja "atômica" sobre a sua utilidade.
É mais interessante a detecção de pessoa ficar isolada em uma classe e a detecção de armas em outra. Desse modo, outro programa vai utilizar objetos das duas classes para executar a análise

**Comment by RodolfoFR** [comment]
Foi criado duas classes diferentes um para pessoa e outra para arma
